version: '3.8'

services:
  mongo-testrs:
    container_name: mongo-testrs
    image: mongo:4.4
    volumes:
      - ./entrypoint.sh:/scripts/entrypoint.sh
    ports:
      - 27021:27021
      - 27022:27022
    entrypoint: [ "/bin/bash", "./scripts/entrypoint.sh"]
