## Publish Beta ##
### REQUIREMENTS ###
# Given a branch name of release/beta/0.3 and a version of 0.3.4

# == GIT TAG ==
# git tag will be created based on the branch name: release/beta/0.3.4
# == PYPI ==
# pypi version is based on the version input: 0.3.4
# == DOCKER ==
# docker images will be tagged based on the above version
# tags: [SHORT_HASH, 0.3, 0.3.4]

name: publish-beta
# SECRETS NAME                   | Description                     | PERMISSIONS
# ------------------------------ | ------------------------------- | ----------------------------------------------------
## GCR_PYPI_CREDENTIALS_RW_B64   | GCloud ServiceAccount B64 JSON  | [Artifact Registry | Python     ] read write
## GCR_DOCKER_CREDENTIALS_R_B64  | GCloud ServiceAccount B64 JSON  | [Artifact Registry | Docker     ] read
## SLACK_OAUTH                   | Slack App OAUTH Token           | [Slack                          ] write message
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: '0.0.0'
permissions:
  contents: write
env:
  # Python
  BETA_PYPI_PROJECT_ID: beta-testing-373907
  BETA_PYPI_REPO: beta-pypi
  BETA_PYPI_LOCATION: us-central1
  POETRY_HTTP_BASIC_FEATUREBYTE_NP_USERNAME: _json_key_base64 # Poetry to pull from google artifact factory [references pyproject.toml (tool.poetry.source).name]
  POETRY_HTTP_BASIC_FEATUREBYTE_NP_PASSWORD: ${{ secrets.GCR_PYPI_CREDENTIALS_R_B64 }} # Poetry to pull from google artifact factory [references pyproject.toml (tool.poetry.source).name]
  # Docker
  IMAGE_REPO: "us-central1-docker.pkg.dev/beta-testing-373907/docker/featurebyte-server"
concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}
jobs:
  publish:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: ["3.8.0"]
    steps:
      - name: Check Version
        run: |
          if (grep -vqP "^[0-9]+[.][0-9]+[.][0-9]+" <<< "${{ github.event.inputs.version }}"); then
              echo "Version must be in the format of '^[0-9]+[.][0-9]+[.][0-9]+'"
              exit 1
          fi
          if (grep -vqP '^release/beta/[0-9]+[.][0-9]+' <<< "${{ github.ref_name }}" ); then
              echo "Branch name must be in the format of 'release/beta/[0-9]+[.][0-9]+'"
              exit 1
          fi
          if (grep -vqP "^${${{ github.ref_name }}#release/beta/}" <<< "${{ github.event.inputs.version }}"); then
              echo "Version must match the branch name"
              exit 1
          fi
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: poetry-cache-${{ runner.os }}-${{ matrix.python-version }}-${{ github.job }}
          restore-keys: poetry-cache-${{ runner.os }}-${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.3.1
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry config http-basic.featurebyte_np ${POETRY_HTTP_BASIC_FEATUREBYTE_NP_USERNAME} ${POETRY_HTTP_BASIC_FEATUREBYTE_NP_PASSWORD}
      - name: Install dependencies
        run: |
          make install
      - name: Bump Version
        run: |
          poetry version -- ${{ github.event.inputs.version }}
      - name: Replace docker-compose image tag
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.services.featurebyte-server.image = "${IMAGE_REPO}:${{ github.event.inputs.version }}"' featurebyte/docker/featurebyte.yml
      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.BETA_ARTIFACT_REGISTRY_RW }}'
      - name: Publish to Google Artifact Registry (PYPI)
        run: |
          poetry config repositories.beta_pypi https://${BETA_PYPI_LOCATION}-python.pkg.dev/${BETA_PYPI_PROJECT_ID}/${BETA_PYPI_REPO}
          poetry publish --build -r beta_pypi --username='_json_key_base64' --password='${{ secrets.BETA_ARTIFACT_REGISTRY_RW }}'
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
      - name: Docker Login Beta Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.BETA_PYPI_PROJECT_ID }}-docker.pkg.dev
          username: _json_key_base64
          password: ${{ secrets.BETA_ARTIFACT_REGISTRY_RW }}
      - name: featurebyte-server args and requirements
        run: |
          echo "SHORT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          make build-hive-udf-jar
          poetry build
      - name: Build & Tag & Push Image to Beta
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:${{ env.SHORT_HASH }}
            ${{ env.IMAGE_REPO }}:${{ github.event.inputs.version }}
            ${{ env.IMAGE_REPO }}:${{ github.ref_name }}
          context: .
          file: docker/Dockerfile
          cache-from: type=registry,ref=${{ env.IMAGE_REPO }}:${{ github.ref_name }}
          cache-to: type=inline
          build-args: FEATUREBYTE_NP_PASSWORD=${{ secrets.GCR_PYPI_CREDENTIALS_R_B64 }}
      - name: Tagging version
        run: |
          git config --global user.name "featurebyte[bot]"
          git config --global user.email "featurebyte[bot]@users.noreply.github.com"
          git tag "release/beta/${{ github.event.inputs.version }}"
          git push origin "release/beta/${{ github.event.inputs.version }}"
  slack:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: ["publish"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Author Email
        if: ${{ github.event_name != 'pull_request' }}
        run: echo "AUTHOR_EMAIL=$(git show -s --format='%ae' "origin/${GITHUB_REF_NAME}")" >> $GITHUB_ENV
      - name: Get Channel ID
        run: |
          export AUTHOR_ID=`curl -X POST -H "Authorization: Bearer ${{ secrets.SLACK_OAUTH }}" -H 'Content-type: application/json; charset=utf-8' https://slack.com/api/users.list | grep -oP $(echo '"id":"\K[^"]+?"(?:(?!"id").)*${AUTHOR_EMAIL}' | envsubst) | grep -oP '^[^"]+'`
          echo "CHANNEL_ID=${AUTHOR_ID}" >> $GITHUB_ENV
      - name: Get Results
        run: |
          echo "PUBLISH_RESULT=${{ needs.publish.result }}" >> $GITHUB_ENV
          echo "REPOSITORY=$(echo '${{ github.repository }}' | cut -d / -f2)" >> $GITHUB_ENV
      - name: Send Slack notification with workflow result.
        if: ${{ env.CHANNEL_ID != '' }}
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_OAUTH }}
        with:
          channel-id: ${{ env.CHANNEL_ID }}
          payload: |
            {
              "text": "${{ env.REPOSITORY }}[${{ github.workflow }}] [${{ env.PUBLISH_RESULT }}]",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "`${{ env.REPOSITORY }} [${{ github.workflow }}]`: ${{ github.event.pull_request.html_url || github.event.head_commit.url || github.repository.html_url }}"
                  }
                }, {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "```publish: [${{ env.PUBLISH_RESULT }}]```"
                  }
                }
              ]
            }
